project: 
  type: website

website:
  title: "Gapminder Data Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: pandoc
      - cosmo
      - brand
    css: styles.css
    toc: true


title: "Gapminder Data Analysis"
output: 
  html:
    dir: docs
navbar:
  left:
    - text: "Home"
      href: index.qmd
    - text: "Life Expectancy and GDP"
      href: life-gdp.qmd
    - text: "Life Expectancy and Population"
      href: life-population.qmd
    - text: "Country Analysis"
      href: country.qmd
